Cocycle/Models/RouteGroup.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Cocycle.Models
{
    public class RouteGroup
    {
        public int Id { get; set; }
        public int RouteId { get; set; }
        public string RequestBy { get; set; }
        public string ApproveBy { get; set; }
        public DateTime RequestDate { get; set; }
        public DateTime ApproveDate { get; set; }
        public Boolean IsApproved { get; set; }

        [ForeignKey("ApproveBy")]
        public ApplicationUser applicationUserApproved { get; set; }

        [ForeignKey("RequestBy")]
        public ApplicationUser applicationUserRequested { get; set; }

        [ForeignKey("RouteId")]
        public Routes routes { get; set; }
        public Boolean IsActive { get; set; }

        public RouteGroup()
        {
            this.ApproveDate = DateTime.Now;
            this.IsActive = true;

        }
    }
}

Cocycle/Controllers/RouteGroupsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using Cocycle.Models;
using Microsoft.AspNet.Identity;

namespace Cocycle.Controllers
{
    public class RouteGroupsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: RouteGroups
        public void fillviewbags()
        {
            ViewBag.States = db.States.ToList();
            ViewBag.Areas = db.Areas.ToList();
            ViewBag.Users = db.Users.ToList();
            ViewBag.Routes = db.Routes.ToList();
        }
        public ActionResult Index()
        {
            fillviewbags();
               var userid = User.Identity.GetUserId();
           
            //return View(db.RouteGroup.ToList());
            return View(db.RouteGroup.Where(x=>x.routes.CreatedBy==userid && x.IsActive == true).OrderByDescending(x => x.Id).ToList());
        }
        public ActionResult MyGroups()
        {
            var userid = User.Identity.GetUserId();
            fillviewbags();
            //return View(db.RouteGroup.ToList());
            return View(db.RouteGroup.Where(x => x.RequestBy == userid && x.IsActive == true).OrderByDescending(x => x.Id).ToList());
        }


        public ActionResult MyRequest()
        {
            var userid = User.Identity.GetUserId();
            fillviewbags();
            //return View(db.RouteGroup.ToList());
            return View(db.RouteGroup.Where(x => x.RequestBy == userid && x.IsActive == true).OrderByDescending(x => x.Id).ToList());
        }
        public ActionResult ViewMembers(int routeid)
        {
            var userid = User.Identity.GetUserId();
            fillviewbags();
            //return View(db.RouteGroup.ToList());
            return View(db.RouteGroup.Where(x => x.RouteId == routeid).OrderByDescending(x => x.Id).ToList());
        }


        // GET: RouteGroups/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RouteGroup routeGroup = db.RouteGroup.Find(id);
            if (routeGroup == null)
            {
                return HttpNotFound();
            }
            return View(routeGroup);
        }

        // GET: RouteGroups/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RouteGroups/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,RequestBy,ApproveBy,RequestDate,ApproveDate,IsApproved")] RouteGroup routeGroup)
        {
            if (ModelState.IsValid)
            {
                db.RouteGroup.Add(routeGroup);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(routeGroup);
        }

        [Authorize]
         [HttpGet]
        public ActionResult RequestToJoin(string requestby,DateTime requestdate,int RouteId)
        {
            RouteGroup routeGroup = new RouteGroup();
            if (ModelState.IsValid)
            {
                routeGroup.RequestBy = requestby;
                routeGroup.RequestDate = requestdate;
                routeGroup.RouteId = RouteId;
                var IsExist = db.RouteGroup.Where(x => x.RouteId == RouteId && x.RequestBy == requestby && x.IsActive == true).FirstOrDefault();
                if (IsExist != null)
                {
                    return RedirectToAction("MyProfile","Account");
                }
                db.RouteGroup.Add(routeGroup);
                db.SaveChanges();
                
                var userid = User.Identity.GetUserId();
                var users = db.Users.Where(s => s.Id == userid).FirstOrDefault();
                //SendMail(users.Email, RouteId);
                return RedirectToAction("MyProfile", "Account", new { tabid = "request-tab" });
            }
            return View(routeGroup);
        }


        public void SendMail(string email,int RouteId)
        {

            var emailaccounts = db.EmailAccount.FirstOrDefault();
            var message = new MailMessage();
            message.From = new MailAddress(emailaccounts.Email);
            message.To.Add(new MailAddress(email));
            message.Subject = "Cocycle Request For Joining Route Group";
            message.Body = "Dear User,<br> your request for joining route No." + RouteId + " has been sent ";
            message.IsBodyHtml = true;
            using (var smtp = new SmtpClient())
            {
                smtp.EnableSsl = emailaccounts.EnableSSL;
                smtp.UseDefaultCredentials = emailaccounts.UseDefaultCredentials;
                var credential = new NetworkCredential
                {
                    UserName = emailaccounts.Email,  // replace with valid value
                    Password = emailaccounts.Password // replace with valid value
                };
                smtp.Credentials = credential;
                smtp.Host = emailaccounts.Host;
                smtp.Port = Convert.ToInt32(emailaccounts.Port);
                smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
                smtp.Send(message);
            }
            //return View(model);
        }

        [Authorize(Roles = "cyclist")]
        public ActionResult AcceptRequest(string ApproveBy, DateTime Approvedate, int RouteGroupId)
        {
            RouteGroup routeGroup = new RouteGroup();
            if (ModelState.IsValid)
            {
                routeGroup = (from r in db.RouteGroup
                              where r.Id == RouteGroupId
                              select r).SingleOrDefault();
                routeGroup.ApproveBy= ApproveBy;
                routeGroup.ApproveDate = Approvedate;
                routeGroup.IsApproved = true;
                db.Entry(routeGroup).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("MyProfile", "Account",new { tabid = "my_route-tab" });
            }
            return View(routeGroup);
        }


        // GET: RouteGroups/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RouteGroup routeGroup = db.RouteGroup.Find(id);
            if (routeGroup == null)
            {
                return HttpNotFound();
            }
            return View(routeGroup);
        }

        // POST: RouteGroups/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,RequestBy,ApproveBy,RequestDate,ApproveDate,IsApproved")] RouteGroup routeGroup)
        {
            if (ModelState.IsValid)
            {
                db.Entry(routeGroup).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(routeGroup);
        }

        // GET: RouteGroups/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RouteGroup routeGroup = db.RouteGroup.Find(id);
            if (routeGroup == null)
            {
                return HttpNotFound();
            }
            return View(routeGroup);
        }

        // POST: RouteGroups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RouteGroup routeGroup = db.RouteGroup.Find(id);
            db.RouteGroup.Remove(routeGroup);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Cocycle/Views/RouteGroups/Create.cshtml
@model Cocycle.Models.RouteGroup

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RouteGroup</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RequestBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RequestBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequestBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApproveBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApproveBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApproveBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequestDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RequestDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequestDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApproveDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApproveDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApproveDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsApproved, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsApproved)
                    @Html.ValidationMessageFor(model => model.IsApproved, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Cocycle/Views/RouteGroups/Delete.cshtml
@model Cocycle.Models.RouteGroup

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container" style="color:black">
    <h2>Delete</h2>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Route Member</h4>
        <hr />
      

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</div>

Cocycle/Views/RouteGroups/Details.cshtml
@model Cocycle.Models.RouteGroup

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>RouteGroup</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RequestBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApproveBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApproveBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApproveDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApproveDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsApproved)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsApproved)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Cocycle/Views/RouteGroups/Index.cshtml
@using Microsoft.AspNet.Identity
@model IEnumerable<Cocycle.Models.RouteGroup>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container pt-5 pb-5">


    <div class="card">
        <div class="card-header">
            <h3>Join Route Request</h3>

        </div>
        <div class="card-body">
            <table class="table" id="tableindex">
                <thead>
                    <tr>
                        <th>
                            RouteNo
                        </th>
                        <th>
                            Request By
                        </th>
                        <th>
                            Request Date
                        </th>

                        <th>
                            @Html.DisplayNameFor(model => model.ApproveDate)
                        </th>
                        <th>
                            Action
                        </th>
                    </tr>
                </thead>
                @foreach (var item in Model)
                {
                    <tbody>
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.routes.Id)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.applicationUserRequested.UserName)
                            </td>
                            <td>
                                @item.RequestDate.ToString("dd-MMM-yyyy")
                            </td>
                            <td>
                                @if (item.IsApproved == true)
                                {
                                    @item.ApproveDate.ToString("dd-MMM-yyyy")
                                }
                            </td>

                            <td>
                                @if (item.IsApproved == true)
                                {
                                    <a href="#">
                                        @Html.ActionLink("Remove", "Delete", "RouteGroups",
                                     new
                                     {
                                         id = item.Id
                                     }, new { @class = "btn btn-sm  btn-danger " })
                                    </a>
                                }
                                else
                                {
                                    <a href="#">
                                        @Html.ActionLink("Approve", "AcceptRequest", "RouteGroups",
                                     new
                                     {
                                         ApproveBy = User.Identity.GetUserId(),
                                         Approvedate = DateTime.Now,
                                         RouteGroupId = item.Id
                                     }, new { @class = "btn btn-sm  btn-success " })
                                    </a>
                                }
                            </td>
                        </tr>
                    </tbody>
                }

            </table>
        </div>
    </div>

    @*<p style="color:black">
            @Html.ActionLink("Create New", "Create")
        </p>*@

</div>



@section Scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/js/jquery.dataTables.min.js"></script>
    <!-- With locals-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment-with-locales.min.js"></script>
    <!-- Without locals-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>



    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            $('#tableindex').DataTable();
        });
    </script>


}

Cocycle/Views/RouteGroups/MyGroups.cshtml
@using Microsoft.AspNet.Identity
@model IEnumerable<Cocycle.Models.RouteGroup>

@{
    ViewBag.Title = "My Route Group";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container pt-5 pb-5">


    <div class="card">
        <div class="card-header">
            <h3>Joined Routes</h3>

        </div>
        <div class="card-body">
            <table class="table" id="tableindex">
                <thead>
                    <tr>
                        <th>
                            RouteNo
                        </th>
                        <th>
                         Route Creator
                        </th>
                        <th>
                            Approved 
                        </th>

                        <th>
                          Phone No.
                        </th>
                        <th>
                            Email
                        </th>
                        <th></th>
                    </tr>
                </thead>
                @foreach (var item in Model)
                {
                    <tbody>
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.routes.Id)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.applicationUserApproved.Name)
                            </td>
                            <td>
                                @item.ApproveDate.ToString("dd-MMM-yyyy")
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.applicationUserApproved.PhoneNumber)

                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.applicationUserApproved.Email)
                            </td>
                            <td>
                                <a href="#">
                                    @Html.ActionLink("View Route", "Details", "Routes",
                                 new
                                 {
                                     Id = @item.RouteId
                                    
                                 }, new { @class = "btn btn-sm  btn-success " })
                                </a>

                            </td>
                        </tr>
                    </tbody>
                }

            </table>
        </div>
    </div>

    @*<p style="color:black">
            @Html.ActionLink("Create New", "Create")
        </p>*@

</div>


@*<div class="event-tab" style="margin: 10px 0px 50px 0px;">
        <div class="container">
            <div class="row">

                <div class="col-lg-12">
                    <div class="tab-content">
                        <div class="tab-one-content inactive active">
                            <div class="event-left-content" id="divlist">

                                @foreach (var item in Model)
                                {
                                    <div class="img-item row">
                                        <div class="col-lg-4">
                                            <div class="row h-100">
                                                <div class="img-left">
                                                    <img src="@Html.DisplayFor(modelItem => item.routes.PosterImage)" alt="">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-8  d-flex align-items-center">
                                            <div class="content">

                                                <h4 style="margin-top: 0px">@Html.DisplayFor(modelItem => item.routes.State.StateName), @Html.DisplayFor(modelItem => item.routes.Area.AreaName) &emsp;<span class="labels">By:  </span> @Html.DisplayFor(modelItem => item.applicationUserRequested.UserName)  </h4>

                                                <h4 style="margin-top: 0px">
                                                    <span class="labels">Departure  -</span> @item.routes.StartTime.ToString("dd MMMM yyyy hh:mm tt")
                                                </h4>
                                                <h4 style="margin-top: 0px">
                                                    <span class="labels">Arrival  -</span>  @item.routes.EndTime.ToString("dd MMMM yyyy hh:mm tt")
                                                </h4>
                                                <h4 style="margin-top: 0px">
                                                    <span class="labels">Departure Point -</span> @Html.DisplayFor(modelItem => item.routes.StartingPoint)
                                                </h4>
                                                <h4 style="margin-top: 0px">
                                                    <span class="labels">Arrival Point -</span> @Html.DisplayFor(modelItem => item.routes.EndPoint)
                                                </h4>
                                                <h4 style="margin-top: 0px">
                                                    <span class="labels">Created Date - </span> @item.routes.Created.ToString("dd-MM-yyyy")
                                                </h4>
                                                <p>@Html.DisplayFor(modelItem => item.routes.Message)</p>
                                                @if (@item.IsApproved == false)
                                                {
                                                    <div class="btn-wrapper">
                                                        <a href="#">
                                                            @Html.ActionLink("Approve Request", "AcceptRequest", "RouteGroups",
                                                         new
                                                         {
                                                             ApproveBy = User.Identity.GetUserId(),
                                                             Approvedate = DateTime.Now,
                                                             RouteGroupId = item.Id
                                                         }, new { @class = "btn btn-element btn-medium btn-red float-right" })
                                                        </a>
                                                    </div>
                                                }
                                                else
                                                {
                                                    <div class="btn-wrapper">
                                                        <a href="#" class="btn-disabled btn-element btn-medium btn-red float-right">
                                                            Request Approved
                                                        </a>
                                                    </div>
                                                }

                                            </div>
                                        </div>
                                    </div>
                                }

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>*@

@section Scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/js/jquery.dataTables.min.js"></script>
    <!-- With locals-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment-with-locales.min.js"></script>
    <!-- Without locals-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>



    @*@Scripts.Render("~/bundles/jqueryval")*@
    <script>
        $(document).ready(function () {
            $('#tableindex').DataTable();
        });
    </script>
}

Cocycle/Views/RouteGroups/ViewMembers.cshtml
@using Microsoft.AspNet.Identity
@model IEnumerable<Cocycle.Models.RouteGroup>

@{
    ViewBag.Title = "ViewMembers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="form-area">
    <div class="container">
        <div class="card" style="box-shadow: #00000017 0px 3px 12px;">
            <div class="card-header" style="background-color: #a5c7b6;font-family: 'Avenir-Bold'">Route Members</div>
            <div class="card-body">
                <table class="table " id="tablerequest" style="color:black">
                    <thead>
                        <tr>
                            <th>
                                RouteNo
                            </th>
                            <th>
                                UserName
                            </th>
                            <th>
                                Requested
                            </th>
                            <th>
                                Approved
                            </th>
                            <th>
                                Status
                            </th>
                            <th>

                            </th>

                        </tr>
                    </thead>


                    @foreach (var item in Model)
                    {
                        <tbody>
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.routes.Id)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.applicationUserRequested.Name)
                                </td>
                                <td>
                                    @item.RequestDate.ToString("dd MMMM yyyy hh:mm tt")
                                </td>
                                <td>
                                    @if (item.IsApproved == true)
                                    {@item.ApproveDate.ToString("dd MMMM yyyy hh:mm tt")}
                                </td>
                                <td>
                                    @if (item.IsApproved == false)
                                    {
                                        <span class="badge badge-warning">Pending</span>
                                    }
                                    else
                                    {
                                        <span class="badge badge-success">Approved</span>
                                    }
                                </td>
                                <td>
                                    @if (item.IsApproved == true)
                                    {
                                        <a href="#">
                                            @Html.ActionLink("Remove", "Delete", "RouteGroups",
                                         new
                                         {
                                             id = item.Id
                                         }, new { @class = "btn  btn-sm btn-danger " })
                                        </a>
                                    }
                                    else
                                    {
                                        <a href="#">
                                            @Html.ActionLink("Approve", "AcceptRequest", "RouteGroups",
                                         new
                                         {
                                             ApproveBy = User.Identity.GetUserId(),
                                             Approvedate = DateTime.Now,
                                             RouteGroupId = item.Id
                                         }, new { @class = "btn  btn-sm btn-red " })
                                        </a>
                                    }
                                </td>
                                @*<td>
                                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                                    </td>*@
                            </tr>
                        </tbody>
                    }

                </table>

            </div>
        </div>


    </div>
</div>

@section Scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/js/jquery.dataTables.min.js"></script>
    <!-- With locals-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment-with-locales.min.js"></script>
    <!-- Without locals-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>



    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            $('#tablerequest').DataTable();
        });
    </script>

}