Cocycle/Controllers/ArrangedsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using Cocycle.Models;
using Microsoft.AspNet.Identity;

namespace Cocycle.Controllers
{
    [Authorize]
    public class ArrangedsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
      
        // GET: Arrangeds


        public void filldropdown()
        {
            ViewBag.States = db.States.Where(x => x.IsActive == true).ToList();
            ViewBag.Areas = db.Areas.Where(x => x.IsActive == true).ToList();
            ViewBag.Users = db.Users.ToList();
        }
        public ActionResult Index()
        {
            filldropdown();
            ViewBag.loggedinuser = User.Identity.GetUserId();
            return View(db.Arranged.Where(x => x.IsScheduled==false && x.IsActive==true).OrderByDescending(x => x.Id).ToList());
        }

      
        public ActionResult IndexLearner()
        {
            filldropdown();
            ViewBag.loggedinuser = User.Identity.GetUserId();
            string userid = User.Identity.GetUserId();
            ViewBag.feedbacks = db.FeedBacks.Where(x=>x.UserId==userid && x.IsActive==true).OrderByDescending(x => x.Id).ToList(); 
            return View(db.Arranged.Where(x=>x.RequestBy== userid && x.IsActive==true).Include(x => x.FeedBack).OrderByDescending(x => x.Id).ToList());
        }
        public ActionResult IndexCyclist()
        {
            filldropdown();
            ViewBag.loggedinuser = User.Identity.GetUserId();
            string userid = User.Identity.GetUserId();
            ViewBag.feedbacks = db.FeedBacks.Where(x => x.UserId == userid && x.IsActive == true).OrderByDescending(x => x.Id).ToList();
            return View(db.Arranged.Where(x => x.ApprovedBy == userid && x.IsActive == true).Include(x=>x.FeedBack).OrderByDescending(x => x.Id).ToList());
        }

        public ActionResult OfferHelp(int Id)
        {

            if (ModelState.IsValid)
            {
                Arranged arranged = (from r in db.Arranged
                                     where r.Id == Id
                                     select r).SingleOrDefault();

                arranged.ApproveDate = DateTime.Now;
                arranged.ApprovedBy = User.Identity.GetUserId();
                arranged.IsApproved = true;
                db.SaveChanges();
                return RedirectToAction("MyProfile", "Account",new { tabid= "arranged-tab" });
                //return RedirectToAction("IndexCyclist", "Arrangeds");
            }
            return RedirectToAction("MyProfile", "Account", new { tabid = "arranged-tab" });
        }
        
        public ActionResult ScheduleDate(int Id,DateTime startdate,string ApproveRemark)
        {
            if (ModelState.IsValid)
            {
                var userid = User.Identity.GetUserId();
                Arranged arranged = (from r in db.Arranged
                                     where r.Id == Id
                                     select r).SingleOrDefault();

                //var schedules = offeringdates.Replace(@"\","");
                //arranged.OfferingDates = schedules;
                arranged.ApproveRemark = ApproveRemark;
                arranged.StartTime = startdate;
                arranged.IsApproved = true;
                arranged.ApprovedBy = userid;
                arranged.IsScheduled = true;
                var users = db.Users.Where(s => s.Id == arranged.RequestBy).FirstOrDefault();
                db.SaveChanges();
                //trigger mail
             //   SendMail(users.Email, Id,arranged.applicationUserApproved.Email);
                return Json(arranged, JsonRequestBehavior.AllowGet);
               
            }
            return RedirectToAction("MyProfile","Account", new { tabid = "arranged-tab" });
        }
        public void SendMail(string email, int rideid,string approvalemail)
        {

            var emailaccounts = db.EmailAccount.FirstOrDefault();
            var message = new MailMessage();
            message.From = new MailAddress(emailaccounts.Email);
            message.To.Add(new MailAddress(email));
            message.Subject = "Cocycle Help Offered for ride";
            message.Body = "Dear User,<br> your request for ride No." + rideid + " has been accepted by the user  "+ approvalemail;
            message.IsBodyHtml = true;
            using (var smtp = new SmtpClient())
            {
                smtp.EnableSsl = emailaccounts.EnableSSL;
                smtp.UseDefaultCredentials = emailaccounts.UseDefaultCredentials;
                var credential = new NetworkCredential
                {
                    UserName = emailaccounts.Email,  // replace with valid value
                    Password = emailaccounts.Password // replace with valid value
                };
                smtp.Credentials = credential;
                smtp.Host = emailaccounts.Host;
                smtp.Port = Convert.ToInt32(emailaccounts.Port);
                smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
                smtp.Send(message);
            }
            //return View(model);
        }

        public ActionResult Confirm(int Id, DateTime confirmdate)
        {

            if (ModelState.IsValid)
            {
                var userid = User.Identity.GetUserId();
                Arranged arranged = (from r in db.Arranged
                                     where r.Id == Id
                                     select r).SingleOrDefault();
                arranged.StartTime = confirmdate;
                //arranged.EndTime = EndDate;
                arranged.IsScheduled = true;
                db.SaveChanges();
                var users = db.Users.Where(s => s.Id == arranged.ApprovedBy).FirstOrDefault();
              //  SendconfirmMail(users.Email, Id);
                return Json(arranged, JsonRequestBehavior.AllowGet);
                // return RedirectToAction("IndexLearner", "Arrangeds");
                // return RedirectToAction("IndexLearner");
            }
            return RedirectToAction("MyProfile", "Account");
        }

        public void SendconfirmMail(string email, int rideid)
        {
            var emailaccounts = db.EmailAccount.FirstOrDefault();
            var message = new MailMessage();
            message.From = new MailAddress(emailaccounts.Email);
            message.To.Add(new MailAddress(email));
            message.Subject = "Cocycle ride date confirmed";
            message.Body = "Dear User,<br> the ride No." + rideid + " has been scheduled ";
            message.IsBodyHtml = true;
            using (var smtp = new SmtpClient())
            {
                smtp.EnableSsl = emailaccounts.EnableSSL;
                smtp.UseDefaultCredentials = emailaccounts.UseDefaultCredentials;
                var credential = new NetworkCredential
                {
                    UserName = emailaccounts.Email,  // replace with valid value
                    Password = emailaccounts.Password // replace with valid value
                };
                smtp.Credentials = credential;
                smtp.Host = emailaccounts.Host;
                smtp.Port = Convert.ToInt32(emailaccounts.Port);
                smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
                smtp.Send(message);
            }
            //return View(model);
        }

        // GET: Arrangeds/Details/5
        public ActionResult Details(int? id)
        {
            filldropdown();
            ViewBag.Routes = db.Routes.Where(x => x.IsActive == true).ToList();
            ViewBag.loggedinuser = User.Identity.GetUserId();
           
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Arranged arranged = db.Arranged.Find(id);
            ViewBag.CyclistFeedback = db.FeedBacks.Where(x => x.RideId == id && x.UserId == arranged.ApprovedBy && x.IsActive==true).FirstOrDefault();
            ViewBag.LearnerFeedback = db.FeedBacks.Where(x => x.RideId == id && x.UserId == arranged.RequestBy && x.IsActive == true).FirstOrDefault();
            if (arranged == null)
            {
                return HttpNotFound();
            }
            return View(arranged);
        }

        public void fill_dropdown()
        {
            List<StateList> liststate = new List<StateList>();
            var lststate = db.States.Where(x => x.IsActive == true).ToList();
            foreach (var s in lststate)
            {
                StateList stateList = new StateList
                {
                    StateId = Convert.ToInt32(s.Id),
                    StateName = s.StateName
                };
                liststate.Add(stateList);
            }
            ViewBag.States = liststate;
            List<Area> Areas = new List<Area>();
            Areas = (from c in db.Areas select c).Where(x => x.IsActive == true).ToList();
            ViewBag.Areas = Areas;

            List<PostCode> postCodes = new List<PostCode>();
            postCodes = (from c in db.postCodes select c).Where(x => x.IsActive == true).ToList();
            ViewBag.postCodes = postCodes;
        }

        [Authorize(Roles = "learner")]
        // GET: Arrangeds/Create
        public ActionResult Create()
        {

            fill_dropdown();

            return View();
        }
        public ActionResult ScheduleDates(int Id)
        {
            ViewBag.ArrangeId = Id;
            var offerdates = db.Arranged.Where(x => x.Id == Id).FirstOrDefault();
            ViewBag.offerdates = offerdates;
            return View("ScheduleDate",offerdates);
        }

        public ActionResult ViewSchedule(int Id)
        {
            //ApplicationDbContext dbContext = new ApplicationDbContext();
            ViewBag.ArrangeId = Id;

Cocycle/Controllers/FeedBacksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Cocycle.Models;
using Microsoft.AspNet.Identity;

namespace Cocycle.Controllers
{
    public class FeedBacksController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: FeedBacks
        public ActionResult Index()
        {
            ViewBag.States = db.States.ToList();
            ViewBag.Areas = db.Areas.ToList();
            ViewBag.Users = db.Users.ToList();
            return View(db.FeedBacks.ToList());

        }

        // GET: FeedBacks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FeedBack feedBack = db.FeedBacks.Find(id);
            if (feedBack == null)
            {
                return HttpNotFound();
            }
            return View(feedBack);
        }

        // GET: FeedBacks/Create
        public ActionResult Create(int id)
        {
           //int rideid = id;
            var feedback = new FeedBack { RideId = id };
            return View(feedback);
        }
        public ActionResult AddRideFeedback(int id)
        {
            //int rideid = id;
            var feedback = new FeedBack { RideId = id };
            return View(feedback);
        }
        public ActionResult AddRouteFeedback(int id)
        {
            //int rideid = id;
            var feedback = new FeedBack { RouteId = id };
            return View(feedback);
        }


        // POST: FeedBacks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddRideFeedback([Bind(Include = "RideId,UserId,description,Created,RideHappened")] FeedBack feedBack)
        {
            if (ModelState.IsValid)
            {
                var userid = User.Identity.GetUserId();
                feedBack.Created = DateTime.Now;
                feedBack.UserId = userid;
                db.FeedBacks.Add(feedBack);
                Arranged a = (from x in db.Arranged where x.Id == feedBack.RideId select x).First();
                a.RideCompleted = true;
                db.SaveChanges();
                return RedirectToAction("MyProfile", "Account");
            }
            return View(feedBack);
        }


        // POST: FeedBacks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddRouteFeedback([Bind(Include = "RideId,RouteId,UserId,description,Created,RideHappened")] FeedBack feedBack)
        {
            if (ModelState.IsValid)
            {
                var userid = User.Identity.GetUserId();
                feedBack.Created = DateTime.Now;
                feedBack.UserId = userid;
                db.FeedBacks.Add(feedBack);
                db.SaveChanges();
                return RedirectToAction("MyProfile", "Account");
            }
            return View(feedBack);
        }



        // POST: FeedBacks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RideId,UserId,description,Created,RideHappened")] FeedBack feedBack)
        {
            if (ModelState.IsValid)
            {
                var userid = User.Identity.GetUserId();
                feedBack.Created = DateTime.Now;
                feedBack.UserId = userid;
                db.FeedBacks.Add(feedBack);
                Arranged a = (from x in db.Arranged where x.Id ==feedBack.RideId select x).First();
                a.RideCompleted = feedBack.RideHappened;
                db.SaveChanges();
                return RedirectToAction("Index","Home");
            }
            return View(feedBack);
        }

        // GET: FeedBacks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FeedBack feedBack = db.FeedBacks.Find(id);
            if (feedBack == null)
            {
                return HttpNotFound();
            }
            return View(feedBack);
        }

        // POST: FeedBacks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,RideId,UserId,description,Created")] FeedBack feedBack)
        {
            if (ModelState.IsValid)
            {
                db.Entry(feedBack).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(feedBack);
        }

        // GET: FeedBacks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FeedBack feedBack = db.FeedBacks.Find(id);
            if (feedBack == null)
            {
                return HttpNotFound();
            }
            return View(feedBack);
        }

        // POST: FeedBacks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            FeedBack feedBack = db.FeedBacks.Find(id);
            db.FeedBacks.Remove(feedBack);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Cocycle/Views/Arrangeds/Delete.cshtml
@model Cocycle.Models.Arranged

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Arranged</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RouteId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RouteId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApprovedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApprovedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartPoint)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartPoint)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.EndPoint)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndPoint)
        </dd>*@

        @*<dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>*@

        @*<dt>
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.RequestRemark)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestRemark)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApproveRemark)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApproveRemark)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApproveDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApproveDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Cocycle/Views/Arrangeds/Edit.cshtml
@model Cocycle.Models.Arranged

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal" style="color:black">
        <h4>Arranged</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)


        <div class="form-group">
            @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequestRemark, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RequestRemark, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequestRemark, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>


}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Cocycle/Views/Arrangeds/IndexLearner.cshtml
@model IEnumerable<Cocycle.Models.Arranged>
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="form-area">
    <div class="container ">


        @*<p>
                @Html.ActionLink("Create New", "Create", null, "@style=color:black")
            </p>*@
        <div class="card" style="box-shadow: #00000017 0px 3px 12px;">
            <div class="card-header" style="background-color: #a5c7b6;font-family: 'Avenir-Bold'">
                My Requested Rides
            </div>
            <div class="card-body">
                <table class="table table-hover" id="tablearranged" style="color:black">
                    <thead>
                        <tr>
                            <th>
                                Ride #.
                            </th>
                            <th>
                                Address
                            </th>
                            <th>
                                Requested Date
                            </th>
                            <th>
                                Help Offered By
                            </th>
                            <th>
                                Ride Schedule
                            </th>
                            <th>
                                Status
                            </th>
                            <th>  Ride Status</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {

                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Id)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.StartPoint)
                                </td>
                                <td>
                                    @item.ApproveDate.ToString("dd-MM-yyyy")
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.applicationUserApproved.UserName)
                                </td>
                                <td>
                                    @if (@item.IsApproved == true)
                                    {
                                        if (item.IsScheduled == true)
                                        {
                                            @item.StartTime.ToString("dd-MMM-yyyy hh:mm tt")
                                        }
                                    }
                                </td>
                                <td>
                                    @if (item.IsApproved == false)
                                    {
                                        <span class="badge badge-warning">Pending</span>
                                    }
                                    else
                                    {
                                        if (item.IsScheduled == false)
                                        {
                                            <a href="#">
                                                @Html.ActionLink("Confirm Date" +
                                               "" +
                                               "", "ViewSchedule",
                                             new { Id = @item.Id }, new { @class = "btn btn-sm btn-success float-right" })
                                            </a>

                                            @*<button type="button" class="btn btn-primary btnschedule" data-id="@item.Id" data-toggle="modal" data-target="#exampleModal">
                                View Schedule
                            </button>*@
                                        }
                                        else
                                        {
                                            if (item.StartTime < DateTime.Now)
                                            {
                                                if (item.FeedBack.Count() > 0)
                                                {
                                                    foreach (var items in item.FeedBack)
                                                    {
                                                        if (User.Identity.GetUserId() == items.UserId)
                                                        {

                                                            <span class="badge badge-success">Feedback Offered</span>
                                                            break;
                                                        }
                                                        else
                                                        {
                                                            <a>@Html.ActionLink("Offer Feedback", "Create", "FeedBacks", new { id = item.Id }, new { @class = "btn btn-red btn-sm" })</a>
                                                        }
                                                    }
                                                }
                                                else
                                                {
                                                    <a>@Html.ActionLink("Offer Feedback", "Create", "FeedBacks", new { id = item.Id }, new { @class = "btn btn-red btn-sm" })</a>
                                                }
                                            }
                                            else
                                            {
                                                <span class="badge badge-success">Scheduled</span>

                                            }
                                        }
                                    }

                                </td>
                                <td>
                                    @if (item.RideCompleted == true)
                                    {
                                        <span class="badge  badge-success m-1"> Completed</span>
                                    }
                                    else
                                    {
                                        <span class="badge  badge-danger m-1">InComplete</span>
                                    }
                                </td>
                                <td> <a> @Html.ActionLink("View", "Details", new { id = item.Id }, new { @class = "btn btn-info btn-sm" })</a>  </td>
                                @*<td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>*@
                            </tr>

                        }
                    </tbody>
                    </table>
            </div>
        </div>


    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Schedule Your Date</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" style="color:black">
                <label class="label-info">Start Date</label>
                <input class="form-control" id="startdate" type="datetime-local" />
                <label class="label-info">End Date</label>
                <input class="form-control" id="enddate" type="datetime-local" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

                <button type="button" class="btn btn-element btn-medium btn-red" id="btnsubmit">
                    @*@Html.ActionLink("Submit", "ScheduleDate","Arrangeds",
                        new { id = 1, StartDate="2021/01/01",EndDate= "2021/01/01" }, new { @class = "btn btn-element btn-medium btn-red " })*@
                    Submit
                </button>

            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/js/jquery.dataTables.min.js"></script>
    <script>
        var ArrangedId;
        $(document).ready(function () {
            $('#tablearranged').DataTable();
        });
        $('.btnschedule').click(function () {
          var id =  $(this).data('id');
            console.log(id);
            ArrangedId = id;
        })

        $('#btnsubmit').click(function (e) {
            e.preventDefault();
            var startdate = $('#startdate').val();
            var enddate = $('#enddate').val();
            var Id = ArrangedId
            //location.href = " /Arrangeds/ScheduleDate/" + Id + "&StartDate=" + startdate + "&EndDate=" + enddate + "";

            obj = { Id: Id, StartDate: startdate, EndDate: enddate}

            $.ajax({
                type: 'POST',
                url: '@Url.Content("~/Arrangeds/ScheduleDate/")',
                data: JSON.stringify(obj),
                dataType: 'json',
                contentType: "application/json",
                success: function (data) {
                    location.reload();
                },
            });
        })
    </script>
}